fieldsDict = {
    'compressor': [
        'user',
        'id',
        'date',
        'gasConsumptionVolume',
        'volumeOfInjectedGas',
        'workingHours',
    ],
    'powerplant': [
        'user',
        'id',
        'date',
        'gasConsumptionVolume',
        'generatedElectricity',
        'workingHours',
    ],
    'boiler': [
        'user',
        'id',
        'date',
        'gasConsumptionVolume',
        'steamVolume',
        'workingHours',
    ],
    'chemical': [
        'user',
        'id',
        'date',
        'gasName',
        'nitrogen',
        'sulfur',
        'carbon',
        'density',
        'CO2EmissionFactor',
        'CH4SpecificFactor',
        'N2OSpecificFactor',
        'LowerHeatCombustion',
    ],
}
