# Generated by Django 3.2.4 on 2021-07-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasTurbineOfCompressors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_consumption_volume', models.IntegerField(null=True)),
                ('volume_of_injected_gas', models.IntegerField(null=True)),
                ('working_hours', models.IntegerField(null=True)),
                ('gas_composition', models.JSONField(null=True)),
                ('waste_gases', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GasTurbinePowerPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HighPressureBoiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
