# Generated by Django 3.2.4 on 2021-07-05 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210705_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasturbineofcompressors',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 21, 25, 59, 29120), null=True),
        ),
    ]
