# Generated by Django 3.2 on 2021-05-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
