# Generated by Django 3.2.4 on 2021-07-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210703_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
