# Generated by Django 3.2.4 on 2021-07-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_gasturbineofcompressors_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasturbineofcompressors',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
