# Generated by Django 3.1.6 on 2021-06-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_userrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRecord',
        ),
    ]
