# Generated by Django 3.2.4 on 2021-07-05 19:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_gasturbineofcompressors_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 7, 6, 1, 59, 23, 742444), null=True)),
                ('gasConsumptionVolume', models.IntegerField(null=True)),
                ('volumeOfInjectedGas', models.IntegerField(null=True)),
                ('workingHours', models.IntegerField(null=True)),
                ('gasComposition', models.JSONField(null=True)),
                ('wasteGases', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='GasCompositionCompressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 7, 6, 1, 59, 23, 741455), null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='gasturbineofcompressors',
            name='user',
        ),
        migrations.DeleteModel(
            name='GasTurbinePowerPlant',
        ),
        migrations.DeleteModel(
            name='HighPressureBoiler',
        ),
        migrations.DeleteModel(
            name='GasTurbineOfCompressors',
        ),
    ]
