# Generated by Django 3.1.6 on 2021-06-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='LargePhoto',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='SmallPhoto',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.JSONField(null=True),
        ),
    ]
