# Generated by Django 3.2.4 on 2021-07-05 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210706_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compressor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 2, 7, 26, 336674), null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='gasComposition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.gascompositioncompressor'),
        ),
        migrations.AlterField(
            model_name='gascompositioncompressor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 2, 7, 26, 335665), null=True),
        ),
    ]
