# Generated by Django 3.2.4 on 2021-07-07 07:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210706_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 7, 7, 13, 35, 36, 933728), null=True)),
                ('facilityName', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.AlterField(
            model_name='compressor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 13, 35, 36, 933728), null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='gasConsumptionVolume',
            field=models.FloatField(help_text='тыс. м3', null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='volumeOfInjectedGas',
            field=models.FloatField(help_text='тыс. м3', null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='wasteGases',
            field=models.FloatField(help_text='г/с', null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='workingHours',
            field=models.FloatField(help_text='часы', null=True),
        ),
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 7, 7, 13, 35, 36, 934728), null=True)),
                ('gasConsumptionVolume', models.FloatField(help_text='тыс. м3', null=True)),
                ('generatedElectricity', models.FloatField(help_text='МВт*ч', null=True)),
                ('workingHours', models.FloatField(help_text='часы', null=True)),
                ('actualPower', models.FloatField(help_text='МВт', null=True)),
                ('gasComposition', models.OneToOneField(help_text='г/с', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.gascomposition')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Boiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 7, 7, 13, 35, 36, 934728), null=True)),
                ('gasConsumptionVolume', models.FloatField(help_text='тыс. м3', null=True)),
                ('steamVolume', models.FloatField(help_text='т', null=True)),
                ('workingHours', models.FloatField(help_text='часы', null=True)),
                ('actualPower', models.FloatField(help_text='МВт', null=True)),
                ('wasteGases', models.FloatField(help_text='г/с', null=True)),
                ('EnthalpySteam', models.FloatField(help_text='кДж/кг', null=True)),
                ('EnthalpyWater', models.FloatField(help_text='кДж/кг', null=True)),
                ('LowerHeatCombustion', models.FloatField(help_text='ТГ, кДж/м3', null=True)),
                ('LowerHeatCombustionNC', models.FloatField(help_text='ТГ при НУ, кДж/м3', null=True)),
                ('gasComposition', models.OneToOneField(help_text='г/с', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.gascomposition')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.AlterField(
            model_name='compressor',
            name='gasComposition',
            field=models.OneToOneField(help_text='г/с', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.gascomposition'),
        ),
        migrations.DeleteModel(
            name='GasCompositionCompressor',
        ),
    ]
