# Generated by Django 3.1.6 on 2021-06-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210621_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.JSONField(default={'large': None, 'small': None}, null=True),
        ),
    ]
