# Generated by Django 3.1.6 on 2021-06-21 08:43

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210621_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.JSONField(default=backend.models.json_default, null=True),
        ),
    ]
