# Generated by Django 3.2.4 on 2021-07-07 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210707_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 13, 55, 3, 274577), null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 13, 55, 3, 273566), null=True),
        ),
        migrations.AlterField(
            model_name='gascomposition',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 13, 55, 3, 273566), null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 13, 55, 3, 274577), null=True),
        ),
    ]
