# Generated by Django 3.2.4 on 2021-07-07 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210707_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 16, 9, 54, 603164), null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 16, 9, 54, 602163), null=True),
        ),
        migrations.AlterField(
            model_name='gascomposition',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 16, 9, 54, 602163), null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 16, 9, 54, 603164), null=True),
        ),
    ]
