# Generated by Django 3.2.4 on 2021-07-07 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210707_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 16, 11, 36, 763229), null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 16, 11, 36, 762229), null=True),
        ),
        migrations.AlterField(
            model_name='gascomposition',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 16, 11, 36, 761230), null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 16, 11, 36, 762229), null=True),
        ),
    ]
