# Generated by Django 3.1.6 on 2021-06-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_userprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
    ]
