# Generated by Django 3.2.4 on 2021-07-07 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210707_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 18, 30, 21, 232772), null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 18, 30, 21, 230771), null=True),
        ),
        migrations.AlterField(
            model_name='gascomposition',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 18, 30, 21, 230771), null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 18, 30, 21, 231781), null=True),
        ),
    ]
