# Generated by Django 3.2.4 on 2021-07-09 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210707_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 20, 0, 27, 261522), null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 20, 0, 27, 260522), null=True),
        ),
        migrations.AlterField(
            model_name='gascomposition',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 20, 0, 27, 259523), null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 20, 0, 27, 260522), null=True),
        ),
    ]
