# Generated by Django 3.2.4 on 2021-07-11 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20210710_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gascomposition',
            name='facilityName',
        ),
        migrations.AddField(
            model_name='gascomposition',
            name='carbon',
            field=models.FloatField(help_text='% масс C', null=True),
        ),
        migrations.AddField(
            model_name='gascomposition',
            name='density',
            field=models.FloatField(help_text='плотность газа', null=True),
        ),
        migrations.AddField(
            model_name='gascomposition',
            name='gasName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gascomposition',
            name='nitrogen',
            field=models.FloatField(help_text='% масс N', null=True),
        ),
        migrations.AddField(
            model_name='gascomposition',
            name='sulfur',
            field=models.FloatField(help_text='% масс S', null=True),
        ),
        migrations.AlterField(
            model_name='boiler',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 11, 14, 53, 31, 290707), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 11, 14, 53, 31, 289708), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gascomposition',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 11, 14, 53, 31, 288707), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 11, 14, 53, 31, 290707), max_length=50, null=True),
        ),
    ]
