# Generated by Django 3.2.4 on 2021-06-27 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscriptions',
        ),
    ]
