# Generated by Django 3.2.4 on 2021-07-11 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20210711_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boiler',
            name='wasteGases',
        ),
        migrations.RemoveField(
            model_name='compressor',
            name='wasteGases',
        ),
        migrations.AlterField(
            model_name='boiler',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 11, 14, 58, 59, 647757), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 11, 14, 58, 59, 646759), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gascomposition',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 11, 14, 58, 59, 645758), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 11, 14, 58, 59, 646759), max_length=50, null=True),
        ),
    ]
