# Generated by Django 3.2.4 on 2021-06-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20210627_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='excel',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
