# Generated by Django 3.2.4 on 2021-07-11 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20210711_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 11, 15, 36, 56, 109191), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 11, 15, 36, 56, 108191), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gascomposition',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 11, 15, 36, 56, 109191), max_length=50, null=True),
        ),
    ]
