# Generated by Django 3.2.4 on 2021-06-27 06:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_userprofile_excel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', cloudinary.models.CloudinaryField(max_length=255, verbose_name='excel')),
            ],
        ),
    ]
