# Generated by Django 3.2.4 on 2021-07-12 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20210711_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boiler',
            name='EnthalpySteam',
        ),
        migrations.RemoveField(
            model_name='boiler',
            name='EnthalpyWater',
        ),
        migrations.RemoveField(
            model_name='boiler',
            name='LowerHeatCombustion',
        ),
        migrations.RemoveField(
            model_name='boiler',
            name='LowerHeatCombustionNC',
        ),
        migrations.RemoveField(
            model_name='boiler',
            name='actualPower',
        ),
        migrations.AddField(
            model_name='gascomposition',
            name='CH4SpecificFactor',
            field=models.IntegerField(help_text='кг/ТДж', null=True),
        ),
        migrations.AddField(
            model_name='gascomposition',
            name='CO2EmissionFactor',
            field=models.FloatField(help_text='тСО2/ТДж', null=True),
        ),
        migrations.AddField(
            model_name='gascomposition',
            name='LowerHeatCombustion',
            field=models.FloatField(help_text='ТГ, ГДж/т', null=True),
        ),
        migrations.AddField(
            model_name='gascomposition',
            name='N2OSpecificFactor',
            field=models.IntegerField(help_text='кг/ТДж', null=True),
        ),
        migrations.AlterField(
            model_name='boiler',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 12, 14, 11, 9, 400112), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 12, 14, 11, 9, 399111), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 12, 14, 11, 9, 400112), max_length=50, null=True),
        ),
    ]
