# Generated by Django 3.2.4 on 2021-07-12 11:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20210712_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 12, 17, 47, 54, 859156), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 12, 17, 47, 54, 857978), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 12, 17, 47, 54, 857978), max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSigned', models.BooleanField(default=False, null=True)),
                ('boiler', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.boiler')),
                ('compressor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.compressor')),
                ('powerPlant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.powerplant')),
            ],
        ),
    ]
