# Generated by Django 3.2.4 on 2021-06-27 06:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20210627_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='excel',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
