# Generated by Django 3.2.4 on 2021-07-14 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20210712_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 14, 14, 6, 7, 33326), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 14, 14, 6, 7, 32337), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gas',
            name='date',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 7, 14, 14, 6, 7, 32337), max_length=50, null=True),
        ),
    ]
