# Generated by Django 3.2.4 on 2021-07-14 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20210715_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='gasComposition',
            field=models.OneToOneField(help_text='г/с', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.gas'),
        ),
        migrations.AlterField(
            model_name='boiler',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='gasComposition',
            field=models.OneToOneField(help_text='г/с', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.gas'),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='gasComposition',
            field=models.OneToOneField(help_text='г/с', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.gas'),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
    ]
