# Generated by Django 3.2.4 on 2021-07-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20210716_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boiler',
            name='isRefused',
        ),
        migrations.RemoveField(
            model_name='compressor',
            name='isRefused',
        ),
        migrations.RemoveField(
            model_name='powerplant',
            name='isRefused',
        ),
        migrations.AddField(
            model_name='boiler',
            name='failureData',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='compressor',
            name='failureData',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='powerplant',
            name='failureData',
            field=models.JSONField(null=True),
        ),
    ]
