# Generated by Django 3.2.4 on 2021-07-16 06:29

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20210716_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='failureData',
            field=models.JSONField(default=backend.models.json_default, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='failureData',
            field=models.JSONField(default=backend.models.json_default, null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='failureData',
            field=models.JSONField(default=backend.models.json_default, null=True),
        ),
    ]
