# Generated by Django 3.2.4 on 2021-07-16 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20210716_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boiler',
            old_name='failureData',
            new_name='refusalData',
        ),
        migrations.RenameField(
            model_name='compressor',
            old_name='failureData',
            new_name='refusalData',
        ),
        migrations.RenameField(
            model_name='powerplant',
            old_name='failureData',
            new_name='refusalData',
        ),
    ]
