# Generated by Django 3.2.4 on 2021-07-16 09:59

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20210716_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='boiler',
            name='isEdited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compressor',
            name='isEdited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gas',
            name='isEdited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gas',
            name='refusalData',
            field=models.JSONField(default=backend.models.json_default, null=True),
        ),
        migrations.AddField(
            model_name='powerplant',
            name='isEdited',
            field=models.BooleanField(default=False),
        ),
    ]
