# Generated by Django 3.2.4 on 2021-07-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20210716_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=None, max_length=50, null=True)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('NO2coef', models.FloatField(default=1)),
                ('NOcoef', models.FloatField(default=1)),
                ('SO2coef', models.FloatField(default=0.02)),
                ('COcoef', models.FloatField(default=1)),
                ('CO2coef', models.FloatField(default=1)),
                ('CH4coef', models.FloatField(default=1)),
                ('N2Ocoef', models.FloatField(default=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
