# Generated by Django 3.2.4 on 2021-07-17 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_formulas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulas',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
    ]
