# Generated by Django 3.2.4 on 2021-07-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_auto_20210717_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=None, max_length=50, null=True)),
                ('compressor', models.JSONField(null=True)),
                ('powerplant', models.JSONField(null=True)),
                ('boiler', models.JSONField(null=True)),
            ],
        ),
    ]
