# Generated by Django 3.2.4 on 2021-07-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='miningDep',
            field=models.JSONField(null=True),
        ),
    ]
