# Generated by Django 3.2.4 on 2021-07-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_archive_miningdep'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='environmentDep',
            field=models.JSONField(null=True),
        ),
    ]
