# Generated by Django 3.2.4 on 2021-07-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_archive_environmentdep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='gasConsumptionVolume',
            field=models.DecimalField(decimal_places=2, help_text='тыс. м3', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='boiler',
            name='steamVolume',
            field=models.DecimalField(decimal_places=2, help_text='т', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='boiler',
            name='workingHours',
            field=models.DecimalField(decimal_places=2, help_text='часы', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='gasConsumptionVolume',
            field=models.DecimalField(decimal_places=2, help_text='тыс. м3', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='volumeOfInjectedGas',
            field=models.DecimalField(decimal_places=2, help_text='тыс. м3', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='workingHours',
            field=models.DecimalField(decimal_places=2, help_text='часы', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='CH4coef',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='CO2coef',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='COcoef',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='N2Ocoef',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='NO2coef',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='NOcoef',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='SO2coef',
            field=models.DecimalField(decimal_places=2, default=0.02, max_digits=3),
        ),
        migrations.AlterField(
            model_name='gas',
            name='CO2EmissionFactor',
            field=models.DecimalField(decimal_places=2, help_text='тСО2/ТДж', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='gas',
            name='LowerHeatCombustion',
            field=models.DecimalField(decimal_places=2, help_text='ТГ, ГДж/т', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='gas',
            name='carbon',
            field=models.DecimalField(decimal_places=2, help_text='% масс C', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='gas',
            name='density',
            field=models.DecimalField(decimal_places=2, help_text='плотность газа', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='gas',
            name='nitrogen',
            field=models.DecimalField(decimal_places=2, help_text='% масс N', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='gas',
            name='sulfur',
            field=models.DecimalField(decimal_places=2, help_text='% масс S', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='gasConsumptionVolume',
            field=models.DecimalField(decimal_places=2, help_text='тыс. м3', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='generatedElectricity',
            field=models.DecimalField(decimal_places=2, help_text='МВт*ч', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='workingHours',
            field=models.DecimalField(decimal_places=2, help_text='часы', max_digits=5, null=True),
        ),
    ]
