# Generated by Django 3.2.4 on 2021-07-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_auto_20210727_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='gasConsumptionVolume',
            field=models.FloatField(help_text='тыс. м3', null=True),
        ),
        migrations.AlterField(
            model_name='boiler',
            name='steamVolume',
            field=models.FloatField(help_text='т', null=True),
        ),
        migrations.AlterField(
            model_name='boiler',
            name='workingHours',
            field=models.FloatField(help_text='часы', null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='gasConsumptionVolume',
            field=models.FloatField(help_text='тыс. м3', null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='volumeOfInjectedGas',
            field=models.FloatField(help_text='тыс. м3', null=True),
        ),
        migrations.AlterField(
            model_name='compressor',
            name='workingHours',
            field=models.FloatField(help_text='часы', null=True),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='CH4coef',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='CO2coef',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='COcoef',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='N2Ocoef',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='NO2coef',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='NOcoef',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='formulas',
            name='SO2coef',
            field=models.FloatField(default=0.02),
        ),
        migrations.AlterField(
            model_name='gas',
            name='CO2EmissionFactor',
            field=models.FloatField(help_text='тСО2/ТДж', null=True),
        ),
        migrations.AlterField(
            model_name='gas',
            name='LowerHeatCombustion',
            field=models.FloatField(help_text='ТГ, ГДж/т', null=True),
        ),
        migrations.AlterField(
            model_name='gas',
            name='carbon',
            field=models.FloatField(help_text='% масс C', null=True),
        ),
        migrations.AlterField(
            model_name='gas',
            name='density',
            field=models.FloatField(help_text='плотность газа', null=True),
        ),
        migrations.AlterField(
            model_name='gas',
            name='nitrogen',
            field=models.FloatField(help_text='% масс N', null=True),
        ),
        migrations.AlterField(
            model_name='gas',
            name='sulfur',
            field=models.FloatField(help_text='% масс S', null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='gasConsumptionVolume',
            field=models.FloatField(help_text='тыс. м3', null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='generatedElectricity',
            field=models.FloatField(help_text='МВт*ч', null=True),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='workingHours',
            field=models.FloatField(help_text='часы', null=True),
        ),
    ]
