# Generated by Django 3.2.4 on 2021-07-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_auto_20210727_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='environmentDep',
            new_name='EPWorker',
        ),
        migrations.RenameField(
            model_name='archive',
            old_name='miningDep',
            new_name='chemical',
        ),
        migrations.AddField(
            model_name='archive',
            name='mining',
            field=models.JSONField(null=True),
        ),
    ]
