# Generated by Django 3.2.4 on 2021-07-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_auto_20210728_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='date',
        ),
    ]
