# Generated by Django 3.2.4 on 2021-09-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
